[build]
rustc = "rustc"
# sccache wrapper, which can significantly improve compilation times by caching previous compilations.
rustc-wrapper = "/usr/local/bin/sccache"
# the default target directory - this reduces overall disk space by compiling everything into
# one directory by default. may also improve compilation times, but no guarantee of that
target-dir = "/Users/jamiegibney/Documents/dev/rust/.CACHE"
rustflags = [
    # this option is best used *only* for development. see more:
    # https://davidlattimore.github.io/posts/2024/02/04/speeding-up-the-rust-edit-build-run-cycle.html#:~:text=Building%20a%20non%2Drelocatable%20executable    
    "-Crelocation-model=static",
]

[target.aarch64-apple.darwin]
rustflags = [
    "-C",
    "link-arg=-fuse-ld=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld",
    "-C",
    "link-arg=-ld_new",
]

[profile.dev]
# the main downside to using this option for development is that backtraces will only
# have function names, and not include line numbers for functions that call a panic.
# to include line/column numbers but not other debug info, use:
debug = "line-tables-only"
split-debuginfo = "unpacked"

[profile.release]
# lto = true
opt-level = 3
debug = false
strip = "symbols"
